---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/instance: gramo
  app.kubernetes.io/name: gramo

images:
- name: docker.io/sebt3/gramo
  newTag: 0.0.9

resources:
- deploy.yaml
- svc.yaml
- sa.yaml
