import { uniq } from "./utils.js";

export const excludedWriteNames = ['metadata','kind','status', 'apiVersion']
export const excludedReadNames = ['metadata','kind', 'apiVersion']
export const defaultResolvers = [];
export const excludes = [
    {group: 'vynil', short: 'Install', for: ['list', 'simple'], values: [{path:'status/tfstate'}, {path:'status/plan'}]},
];
const uses = [
    {algo: 'vynil', group: 'vynil', short: 'Install', usedGroup: 'vynil', usedShort: 'Package', path: null},
    {algo: 'vynil', group: 'vynil', short: 'Install', usedGroup: 'vynil', usedShort: 'Distrib', path: null},
    {algo: 'vynil', group: 'vynil', short: 'Install', usedGroup: 'vynil', usedShort: 'Category', path: null},
    {algo: 'nodeName',  group: 'k8s', short: 'Pod', usedGroup: 'k8s', usedShort: 'Node', path: null},
    {algo: 'serviceAccount',  group: 'k8s', short: 'Pod', usedGroup: 'k8s', usedShort: 'ServiceAccount', path: null},
    {algo: 'ingress',  group: 'k8s', short: 'Ingress', usedGroup: 'k8s', usedShort: 'Service', path: null},
    {algo: 'selector',  group: 'k8s', short: 'Service', usedGroup: 'k8s', usedShort: 'Pod', path: 'metadata'},
    {algo: 'selector',  group: 'k8s', short: 'Service', usedGroup: 'k8s', usedShort: 'ReplicaSet', path: 'spec/template/metadata'},
    {algo: 'selector',  group: 'k8s', short: 'Service', usedGroup: 'k8s', usedShort: 'Deployment', path: 'spec/template/metadata'},
    {algo: 'selector',  group: 'k8s', short: 'Service', usedGroup: 'k8s', usedShort: 'DaemonSet', path: 'spec/template/metadata'},
    {algo: 'selector',  group: 'k8s', short: 'Service', usedGroup: 'k8s', usedShort: 'PodTemplate', path: 'template/metadata'},
    {algo: 'pvc',  group: 'k8s', short: 'PersistentVolumeClaim', usedGroup: 'k8s', usedShort: 'PersistentVolume', path: null},
    {algo: 'pvc',  group: 'k8s', short: 'Pod', path: 'spec', usedGroup: 'k8s', usedShort: 'PersistentVolumeClaim'},
    {algo: 'pvc',  group: 'k8s', short: 'ReplicaSet', path: 'spec/template/spec', usedGroup: 'k8s', usedShort: 'PersistentVolumeClaim'},
    {algo: 'pvc',  group: 'k8s', short: 'Job', path: 'spec/template/spec', usedGroup: 'k8s', usedShort: 'PersistentVolumeClaim'},
    {algo: 'pvc',  group: 'k8s', short: 'CronJob', path: 'spec/jobTemplate/spec/template/spec', usedGroup: 'k8s', usedShort: 'PersistentVolumeClaim'},
    {algo: 'pvc',  group: 'k8s', short: 'Deployment', path: 'spec/template/spec', usedGroup: 'k8s', usedShort: 'PersistentVolumeClaim'},
    {algo: 'pvc',  group: 'k8s', short: 'DaemonSet', path: 'spec/template/spec', usedGroup: 'k8s', usedShort: 'PersistentVolumeClaim'},
    {algo: 'pvc',  group: 'k8s', short: 'PodTemplate', path: 'template/spec', usedGroup: 'k8s', usedShort: 'PersistentVolumeClaim'},
    {algo: 'secret',  group: 'k8s', short: 'Pod', path: 'spec', usedGroup: 'k8s', usedShort: 'Secret'},
    {algo: 'secret',  group: 'k8s', short: 'ReplicaSet', path: 'spec/template/spec', usedGroup: 'k8s', usedShort: 'Secret'},
    {algo: 'secret',  group: 'k8s', short: 'Job', path: 'spec/template/spec', usedGroup: 'k8s', usedShort: 'Secret'},
    {algo: 'secret',  group: 'k8s', short: 'CronJob', path: 'spec/jobTemplate/spec/template/spec', usedGroup: 'k8s', usedShort: 'Secret'},
    {algo: 'secret',  group: 'k8s', short: 'Deployment', path: 'spec/template/spec', usedGroup: 'k8s', usedShort: 'Secret'},
    {algo: 'secret',  group: 'k8s', short: 'DaemonSet', path: 'spec/template/spec', usedGroup: 'k8s', usedShort: 'Secret'},
    {algo: 'secret',  group: 'k8s', short: 'PodTemplate', path: 'template/spec', usedGroup: 'k8s', usedShort: 'Secret'},
    {algo: 'configMap',  group: 'k8s', short: 'Pod', path: 'spec', usedGroup: 'k8s', usedShort: 'ConfigMap'},
    {algo: 'configMap',  group: 'k8s', short: 'ReplicaSet', path: 'spec/template/spec', usedGroup: 'k8s', usedShort: 'ConfigMap'},
    {algo: 'configMap',  group: 'k8s', short: 'Job', path: 'spec/template/spec', usedGroup: 'k8s', usedShort: 'ConfigMap'},
    {algo: 'configMap',  group: 'k8s', short: 'CronJob', path: 'spec/jobTemplate/spec/template/spec', usedGroup: 'k8s', usedShort: 'ConfigMap'},
    {algo: 'configMap',  group: 'k8s', short: 'Deployment', path: 'spec/template/spec', usedGroup: 'k8s', usedShort: 'ConfigMap'},
    {algo: 'configMap',  group: 'k8s', short: 'DaemonSet', path: 'spec/template/spec', usedGroup: 'k8s', usedShort: 'ConfigMap'},
    {algo: 'configMap',  group: 'k8s', short: 'PodTemplate', path: 'template/spec', usedGroup: 'k8s', usedShort: 'ConfigMap'},
];
const provides = [
    {algo: 'vynil', group: 'vynil', short: 'Distrib', providedGroup: 'vynil', providedShort: 'Package'},
    {algo: 'vynil', group: 'vynil', short: 'Distrib', providedGroup: 'vynil', providedShort: 'Category'},
//    {algo: 'vynil', group: 'vynil', short: 'Category', providedGroup: 'vynil', providedShort: 'Package'},
    {algo: 'storageClass', group: 'k8s', short: 'StorageClass', providedGroup: 'k8s', providedShort: 'PersistentVolume'},
    {algo: 'storageClass', group: 'k8s', short: 'StorageClass', providedGroup: 'k8s', providedShort: 'PersistentVolumeClaim'},
    {algo: 'apiService',   group: 'k8s', short: 'APIService', providedGroup: 'k8s', providedShort: 'CustomResourceDefinition'},
    {algo: 'role',         group: 'k8s', short: 'RoleBinding', providedGroup: 'k8s', providedShort: 'Role'},
    {algo: 'roleBinding',  group: 'k8s', short: 'ServiceAccount', providedGroup: 'k8s', providedShort: 'RoleBinding'},
    {algo: 'role',         group: 'k8s', short: 'ClusterRoleBinding', providedGroup: 'k8s', providedShort: 'ClusterRole'},
    {algo: 'roleBinding',  group: 'k8s', short: 'ServiceAccount', providedGroup: 'k8s', providedShort: 'ClusterRoleBinding'},
];
const children = [
    {algo: 'k8s', group: 'k8s', short: 'ReplicaSet', parentGroup: 'k8s', parentShort: 'Deployment'},
    {algo: 'k8s', group: 'k8s', short: 'Pod', parentGroup: 'k8s', parentShort: 'ReplicaSet'},
    {algo: 'k8s', group: 'k8s', short: 'Pod', parentGroup: 'k8s', parentShort: 'StatefulSet'},
    {algo: 'k8s', group: 'k8s', short: 'Pod', parentGroup: 'k8s', parentShort: 'DaemonSet'},
    {algo: 'k8s', group: 'k8s', short: 'Pod', parentGroup: 'k8s', parentShort: 'Job'},
    {algo: 'k8s', group: 'k8s', short: 'Pod', parentGroup: 'cnpg', parentShort: 'Cluster'},
//    {algo: 'k8s', group: 'k8s', short: 'ControllerRevision', parentGroup: 'k8s', parentShort: 'DaemonSet'},
//    {algo: 'k8s', group: 'k8s', short: 'ControllerRevision', parentGroup: 'k8s', parentShort: 'StatefulSet'},
    {algo: 'k8s', group: 'k8s', short: 'Job', parentGroup: 'k8s', parentShort: 'CronJob'},
    {algo: 'k8s', group: 'k8s', short: 'Secret', parentGroup: 'secretgenerator', parentShort: 'BasicAuth'},
    {algo: 'k8s', group: 'k8s', short: 'Secret', parentGroup: 'secretgenerator', parentShort: 'SSHKeyPair'},
    {algo: 'k8s', group: 'k8s', short: 'Secret', parentGroup: 'secretgenerator', parentShort: 'StringSecret'},
    {algo: 'k8s', group: 'k8s', short: 'Secret', parentGroup: 'cnpg', parentShort: 'Cluster'},
    {algo: 'k8s', group: 'k8s', short: 'Secret', parentGroup: 'mongodb', parentShort: 'MongoDBCommunity'},
    {algo: 'k8s', group: 'k8s', short: 'Service', parentGroup: 'mongodb', parentShort: 'MongoDBCommunity'},
    {algo: 'k8s', group: 'k8s', short: 'Service', parentGroup: 'redis', parentShort: 'Redis'},
    {algo: 'k8s', group: 'k8s', short: 'Service', parentGroup: 'cnpg', parentShort: 'Pooler'},
    {algo: 'k8s', group: 'k8s', short: 'Service', parentGroup: 'cnpg', parentShort: 'Cluster'},
    {algo: 'k8s', group: 'k8s', short: 'Service', parentGroup: 'monitoring', parentShort: 'Prometheus'},
    {algo: 'k8s', group: 'k8s', short: 'Service', parentGroup: 'monitoring', parentShort: 'Alertmanager'},
    {algo: 'k8s', group: 'k8s', short: 'EndpointSlice', parentGroup: 'k8s', parentShort: 'Service'},
    {algo: 'k8s', group: 'k8s', short: 'StatefulSet', parentGroup: 'mongodb', parentShort: 'MongoDBCommunity'},
    {algo: 'k8s', group: 'k8s', short: 'StatefulSet', parentGroup: 'redis', parentShort: 'Redis'},
    {algo: 'k8s', group: 'k8s', short: 'StatefulSet', parentGroup: 'monitoring', parentShort: 'Prometheus'},
    {algo: 'k8s', group: 'k8s', short: 'StatefulSet', parentGroup: 'monitoring', parentShort: 'Alertmanager'},
    {algo: 'k8s', group: 'k8s', short: 'ServiceAccount', parentGroup: 'cnpg', parentShort: 'Pooler'},
    {algo: 'k8s', group: 'k8s', short: 'ServiceAccount', parentGroup: 'cnpg', parentShort: 'Cluster'},
    {algo: 'k8s', group: 'k8s', short: 'PodDisruptionBudget', parentGroup: 'cnpg', parentShort: 'Cluster'},
    {algo: 'k8s', group: 'k8s', short: 'ConfigMap', parentGroup: 'monitoring', parentShort: 'Prometheus'},
    {algo: 'k8s', group: 'k8s', short: 'Deployment', parentGroup: 'cnpg', parentShort: 'Pooler'},
    {algo: 'k8s', group: 'k8s', short: 'Role', parentGroup: 'cnpg', parentShort: 'Cluster'},
    {algo: 'k8s', group: 'k8s', short: 'Role', parentGroup: 'cnpg', parentShort: 'Pooler'},
    {algo: 'k8s', group: 'k8s', short: 'RoleBinding', parentGroup: 'cnpg', parentShort: 'Cluster'},
    {algo: 'k8s', group: 'k8s', short: 'RoleBinding', parentGroup: 'cnpg', parentShort: 'Pooler'},
    {algo: 'k8s', group: 'k8s', short: 'PersistentVolumeClaim', parentGroup: 'cnpg', parentShort: 'Cluster'},
    {algo: 'k8s', group: 'k8s', short: 'PersistentVolumeClaim', parentGroup: 'k8s', parentShort: 'StatefulSet'},
];
type autoResolver = {algo: string,type: string,group: string,short: string,targetGroup: string,targetShort: string, path?: string|null}
export const autoResolvers = ([] as autoResolver[]).concat(
    children.map(c=>{return {type: 'parent', group: c.group, short: c.short, targetGroup: c.parentGroup, targetShort: c.parentShort, algo: c.algo}}),
    children.map(c=>{return {type: 'child', group: c.parentGroup, short: c.parentShort, targetGroup: c.group, targetShort: c.short, algo: c.algo}}),
    provides.map(c=>{return {type: 'provide', group: c.group, short: c.short, targetGroup: c.providedGroup, targetShort: c.providedShort, algo: c.algo}}),
    provides.map(c=>{return {type: 'providedTo', group: c.providedGroup, short: c.providedShort, targetGroup: c.group, targetShort: c.short, algo: c.algo}}),
    uses.map(c=>{return {type: 'use', group: c.group, short: c.short, targetGroup: c.usedGroup, targetShort: c.usedShort, algo: c.algo, path: c.path}}),
    uses.map(c=>{return {type: 'usedBy', group: c.usedGroup, short: c.usedShort, targetGroup: c.group, targetShort: c.short, algo: c.algo, path: c.path}}),
)
export const extraResolvers = autoResolvers.map(a=>{return {
    group: a.group, short: a.short, type: a.type, name: `${a.type}${a.targetShort}`, args: "(params: queryParameters)", resultGroup: a.targetGroup, resultShort: a.targetShort, result: `[${a.targetGroup}${a.targetShort}]`
}}).concat ()

const categoryOrder = [
    'install',
    'automation',
    'workload',
    'database',
    'storage',
    'config',
    'network',
    'security',
    'system'
];

export const categoryMappingGroup = {
    cnpg: 'database',
    zalando: 'database',
    mariadb: 'database',
    mongodb: 'database',
    oracle: 'database',
    rabbitmq: 'database',
    redis: 'database',
    fluxcd: 'automation',
    traefik: 'network',
    certmanager: 'network',
    projectcalico: 'network',
    monitoring: 'system',
    opentelemetry: 'system',
    jaegertracing: 'system',
    k8up: 'system',
    k8s: 'system',
    secretgenerator: 'config',
    vynil: 'install',
}
export const categoryMappingShort = {
    StatefulSet: 'workload',
    CronJob: 'workload',
    DaemonSet: 'workload',
    Deployment: 'workload',
    Job: 'workload',
    PodTemplate: 'workload',
    Pod: 'workload',
    ReplicaSet: 'workload',
    HorizontalPodAutoscaler: 'workload',
    ConfigMap: 'config',
    Secret: 'config',
    ClusterRoleBinding: 'security',
    ClusterRole: 'security',
    RoleBinding: 'security',
    Role: 'security',
    ServiceAccount: 'security',
    NetworkPolicy: 'security',
    Endpoints: 'network',
    Ingress: 'network',
    Service: 'network',
    EndpointSlice: 'network',
    CSIDriver: 'storage',
    CSINode: 'storage',
    CSIStorageCapacity: 'storage',
    PersistentVolumeClaim: 'storage',
    PersistentVolume: 'storage',
    StorageClass: 'storage',
    VolumeAttachment: 'storage',
    CertificateSigningRequest: 'security',
    ControllerRevision: 'workload',
    PodDisruptionBudget: 'workload',
    PriorityClass: 'workload',
    ResourceQuota: 'workload',
    RuntimeClass: 'workload',
    LimitRange: 'workload',
    ReplicationController: 'workload',
}
export const allCategories = Object.entries(categoryMappingShort).map(([_,v])=>v)
        .concat(Object.entries(categoryMappingGroup).map(([_,v])=>v))
        .filter(uniq).sort((a,b)=>categoryOrder.indexOf(a)<categoryOrder.indexOf(b)?-1:1)