---
steps:
  lint-docker:
    group: lint
    image: hadolint:latest-alpine
    commands:
    - hadolint agent/Dockerfile
  gen-tags:
    image: alpine:latest
    commands:
    - awk '$1~/"version":/{print $2}' package.json |sed 's/"//g;s/,//'>.tags
  build:
    group: build
    image: woodpeckerci/plugin-docker-buildx
    volumes:
    - cache:/var/lib/docker
    settings:
      mount:
      - "cache"
      repo: git.solidite.fr/${CI_REPO_OWNER}/${CI_REPO_NAME},sebt3/${CI_REPO_NAME}
      dockerfile: Dockerfile
      tags_file: .tags
      platforms: linux/amd64,linux/arm64/v8
      logins:
      - registry: git.solidite.fr
        username:
          from_secret: repo_user
        password:
          from_secret: repo_password
      - registry: https://index.docker.io/v1/
        username:
          from_secret: docker_user
        password:
          from_secret: docker_password
